### ISSUE TITLE
Issue when running prediction using a new trained model

### ISSUE THREAD

**Issue by mikeefriedman** [AI-sandbox/XGMix#16]
Hi,

I am trying to run a pre-trained set (chr 22) of 170 individuals but I get the following error. The model was trained with the default configuration.

Launching XGMix in pre-trained mode...
Loading model...
Loading and processing query file...
- Number of SNPs from model: 2170
- Number of SNPs from file: 424147
- Number of intersecting SNPs: 2170
- Percentage of model SNPs covered by query file: 100.0%
- Found 725 (33.3947%) different reference variants. Adjusting...
Inferring ancestry on query data...
Phasing individual 1/1Traceback (most recent call last):
  File "XGMix-master\XGMIX.py", line 365, in <module>
    main(args, verbose=verbose, run_simulation=run_simulation, founders_ratios=founders_ratios,
  File "XGMix-master\XGMIX.py", line 285, in main
    X_query_phased, label_pred_query_window = model.phase(X_query)
  File "XGMix-master\Utils\XGMix.py", line 343, in phase
    X_m, X_p, Y_m, Y_p, history, XGFix_tracker = XGFix(X_m, X_p, base_prob=base_prob, smoother=self.smooth, verbose=verbose)
  File "XGMix-master\XGFix\XGFIX.py", line 197, in XGFix
    outs = outs.reshape(-1,2,A)
ValueError: cannot reshape array of size 24 into shape (2,39)

Thanks.

**Comment by weekend37** [comment]
Hi mikeefriedman and thanks for letting us know. 
Before I dig into this, could you try our [newly released codebase](https://github.com/AI-sandbox/gnomix) and see if you get the same error?
If so, please leave open an issue in that repo and I'll make sure we fix it asap.
Thanks again.
