### ISSUE TITLE
config.py settings explanation

### ISSUE THREAD

**Issue by m1sorenson** [AI-sandbox/XGMix#17]
Hi! I am at the Nievergelt lab (UCSD), and we are trying to use XGMix for local ancestry inference. Could you explain more how the advanced configuration affects the algorithm, and what they mean? The README says "More details are given in the file [config.py] itself.", but there doesn't seem to be much in the config.py to go off of.

**Comment by weekend37** [comment]
Hi m1sorenson!
We're pleased to hear that you're using our software and thank you for this good note.
We've been developing a new codebase and going back and forth with the config file in the meantime.
The updated version of the code can now be found [here](https://github.com/AI-sandbox/gnomix) where the advanced configurations are better described. 
Let me know there if you have any more questions on that.
